# Generated by Django 4.2.4 on 2023-08-07 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
