# Generated by Django 4.2.4 on 2023-08-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='MembersChat',
        ),
    ]
