# Generated by Django 4.2.4 on 2023-08-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_members_memberschat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MembersChat',
            new_name='MembersChatt',
        ),
    ]
