# Generated by Django 4.2.4 on 2023-08-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nom',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='prenom',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
    ]
